# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 12:07
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20180814_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='art',
            name='summary',
            field=models.CharField(max_length=500, verbose_name='简介'),
        ),
    ]
